# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  RunEngine_config = debug
  Application_config = debug
  glfw_config = debug

else ifeq ($(config),release)
  RunEngine_config = release
  Application_config = release
  glfw_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := RunEngine Application glfw

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

RunEngine: glfw
ifneq (,$(RunEngine_config))
	@echo "==== Building RunEngine ($(RunEngine_config)) ===="
	@${MAKE} --no-print-directory -C src -f Makefile config=$(RunEngine_config)
endif

Application: RunEngine glfw
ifneq (,$(Application_config))
	@echo "==== Building Application ($(Application_config)) ===="
	@${MAKE} --no-print-directory -C application -f Makefile config=$(Application_config)
endif

glfw:
ifneq (,$(glfw_config))
	@echo "==== Building glfw ($(glfw_config)) ===="
	@${MAKE} --no-print-directory -C GLFW -f Makefile config=$(glfw_config)
endif

clean:
	@${MAKE} --no-print-directory -C src -f Makefile clean
	@${MAKE} --no-print-directory -C application -f Makefile clean
	@${MAKE} --no-print-directory -C GLFW -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   RunEngine"
	@echo "   Application"
	@echo "   glfw"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"